### ISSUE TITLE
Deliverables 1/16

### ISSUE THREAD

**Issue by bstadt** [NeuroDataDesign/pan-synapse#23]
Be able to run a subsection of real world data through the pipeline and generate naive statistics about it (i.e. identify & separate clusters, retrieve cluster area, and density of clusters in a given volume)

**Comment by bstadt** [comment]
WILL's WEEKLY GOAL:
     finish naive cluster stats methods (i.e. area, standard deviation from centroid, centroid, density)
BRANDON's WEEKLY GOAL:
     finish writing tests for the existing cluster and connection lib code, and fix any errors
     perform full pipeline analysis testing and debugging on real world data

**Comment by jovo** [comment]
@bstadt 

- [ ] pseudocode, same deal as #orange-pandas, make sure each mathematical object lives in a very clear space, for all inputs and outputs.
- [ ] i did not understand the details of the simulations.  please provide proper extensive description of the generative distribution.
- [ ] seems like you computed PD, but what about false positives? use ROC curve instead?
- [ ] do something for real world data
- [ ] comment on algorithms.md in paragraph form about what you like and what you didn't, what wasn't clear.
