### ISSUE TITLE
Deliverables 2/6

### ISSUE THREAD

**Issue by levinwil** [NeuroDataDesign/pan-synapse#45]
Status | Deliverable | Notes
---------|-----------------|---------
Complete | Clean up repo | All 
Complete | Flask Back-End from one file to Request Handler, Request Dispatcher, Event Threads | Richard (Brandon will help)
Complete | Frontend GUI with registration | Will 
Complete | Line Visualization | Will
Complete | Reach out to Richard about UI Meeting | All
Complete | Generate and send data to Daniel | Brandon
In Progress | Be On Time | Brandon 

https://github.com/NeuroDataDesign/pan-synapse/blob/master/figures/service_asyc_handshake.png
# Live Demo!!

**Comment by jovo** [comment]
@bstadt and meeting with @dtward to discuss measure matching? as soon as possible would be great....

and please email richard asap as well, cc me & @gkiar 

also, make sure to commit to things that are in your control.  eg, "UI meeting with richard" is a nice goal, but you can commit to sending email with availability by tonight, to maximize prob of meeting with him this week".

**Comment by bstadt** [comment]
Already Met with @dtward to discuss matching, will E-Mail Richard immediately

**Comment by rmarren1** [comment]
https://github.com/NeuroDataDesign/orange-panda/issues/34

you can use this if you don't want to do socket level programming
