### ISSUE TITLE
Deliverables for 2/27

### ISSUE THREAD

**Issue by levinwil** [NeuroDataDesign/pan-synapse#48]
**Thursday** 
Status | Deliverable | Notes
---------|-----------------|---------
Complete| Implement scipy volume thresholding pre-cluster and sparse arrays. | Will
Complete | Research alternative algorithms to PLOS | Richard
Complete | Research alternative algorithms to PLOS | Brandon

**Monday**
Status | Deliverable | Notes
---------|-----------------|---------
Complete | Algorithms md notebook on thresholding and sparse arrays: [link to notebook](https://github.com/NeuroDataDesign/pan-synapse/blob/master/background/Cluster_Thresh_Algorithms.md.ipynb)  | Will
Complete | Algorithms md notebook on alternative algorithms for PLOS | Richard
Complete | Algorithms md notebook on density thresholding  [Link](https://nbviewer.jupyter.org/github/NeuroDataDesign/pan-synapse/blob/master/background/neighborhoodDensity.md.ipynb ) | Brandon

Richard's Mon Notebook:
http://nbviewer.jupyter.org/github/NeuroDataDesign/pan-synapse/blob/master/background/PlosAlternatives.ipynb
Brandon's Thurs Notebook:
https://github.com/NeuroDataDesign/pan-synapse/blob/master/background/NeighborhoodDensity.ipynb

**Comment by gkiar** [comment]
@bstadt:
  - what part of the PLOS pipeline will you be investigating replacing? Are there any pieces worth keeping?

@rguo123:
  - what part of the PLOS pipeline will you be investigating replacing? Will it be a different problem from what @bstadt is solving (certainly different alg, but different processing step too?)?

@levinwil:
  - what will you show me as proof for Thursday?

**Comment by rguo123** [comment]
Hey Greg,
I would like to just start off the week looking into other algorithms that can reduce background noise based off of either pixel intensity or size. Do you know any specific methods that I should look into? If there isn't anything in particular you think I should start with, I will present to you a summary of anything I find on Thursday and we can go from there?

Thanks!

**Comment by levinwil** [comment]
Hey Greg,

As of right now, I have a couple very fast algorithms that work very well that are all on different notebooks. What I hope to do for Thursday is to unify all of these algorithms into one single function that I can use to perform the entire second half of our pipeline. For Thursday, I'd like to describe which algorithms I am using for which step in a notebook, and to also run this unified function with a single line and show that it produced the same results as it did before when I was running the data through a series of independent step algorithms and passing the data from one algorithm to the other (a.k.a. to show that I properly unified the algorithms into one algorithm that properly executes the second half of our pipeline). 

I'd like to get this done for Thursday because it will allow Richard and Brandon to actually get average volumes and densities so that they can tell if a PLOS alternative is more or less effective than PLOS, which I think will be really useful for benchmarking.

Thanks

**Comment by bstadt** [comment]
@gkiar It has become apparent that PLOS is simply not well suited to the problem that we are trying to solve. I would be looking to replace the entire thing with some other type of noise reduction. Richard and I believe that there are a variety of alternatives, and we would both like to implement different ones to gauge which may be better.
